"""Sale repository — create sales and run aggregation/report queries.

All queries are parameterized and leverage date indexes for performance.
"""

import sqlite3

from pos.model.sale import Sale
from pos.model.enums import PaymentMethod


class SaleRepo:
    """Data-access for the ``sales`` table."""

    # Allowed strftime format strings for ``aggregate_by_period``.
    _GROUP_FORMATS: dict[str, str] = {
        "day":    "%Y-%m-%d",
        "week":   "%Y-%W",
        "month":  "%Y-%m",
        "year":   "%Y",
    }

    def __init__(self, db: sqlite3.Connection) -> None:
        self._db = db

    # ----------------------------------------------------------------- create

    def create(self, sale: Sale) -> Sale:
        """Insert a sale record. ``created_at`` is generated by SQLite.

        Returns the sale with ``id`` and ``created_at`` populated.
        """
        pm = sale.payment_method.value if isinstance(sale.payment_method, PaymentMethod) else sale.payment_method
        cur = self._db.execute(
            """INSERT INTO sales (total, discount, surcharge, payment_method, cash_register_id)
               VALUES (?, ?, ?, ?, ?)
               RETURNING id, created_at""",
            (sale.total, sale.discount, sale.surcharge, pm, sale.cash_register_id),
        )
        row = cur.fetchone()
        sale.id = row["id"]
        sale.created_at = row["created_at"]
        return sale

    # ------------------------------------------------------------ aggregate

    def aggregate_by_period(
        self, start_date: str, end_date: str, group_by: str
    ) -> list[dict]:
        """Aggregate sales by time period.

        Args:
            start_date: ISO-like datetime string (inclusive).
            end_date:   ISO-like datetime string (inclusive).
            group_by:   One of ``"day"``, ``"week"``, ``"month"``, ``"year"``.

        Returns:
            List of dicts with keys: ``period``, ``sale_count``, ``total_revenue``.
        """
        fmt = self._GROUP_FORMATS.get(group_by, self._GROUP_FORMATS["day"])
        rows = self._db.execute(
            f"""SELECT strftime('{fmt}', created_at) AS period,
                       COUNT(*)   AS sale_count,
                       SUM(total) AS total_revenue
                FROM sales
                WHERE created_at >= ? AND created_at <= ?
                GROUP BY period
                ORDER BY period""",
            (start_date, end_date),
        ).fetchall()
        return [dict(r) for r in rows]

    # ----------------------------------------------------------- top-10 -----

    def top_products(
        self, start_date: str, end_date: str, limit: int = 10
    ) -> list[dict]:
        """Return the top *N* products sold in the given period.

        Returns:
            List of dicts with keys: ``product_id``, ``name``, ``barcode``,
            ``unit_type``, ``total_quantity``, ``total_amount``.
        """
        rows = self._db.execute(
            """SELECT p.id          AS product_id,
                      p.name        AS name,
                      p.barcode     AS barcode,
                      p.unit_type   AS unit_type,
                      SUM(si.quantity) AS total_quantity,
                      SUM(si.subtotal) AS total_amount
               FROM sale_items si
               JOIN products p ON p.id = si.product_id
               JOIN sales    s ON s.id = si.sale_id
                WHERE s.created_at >= ? AND s.created_at <= ?
               GROUP BY p.id
               ORDER BY total_quantity DESC
               LIMIT ?""",
            (start_date, end_date, limit),
        ).fetchall()
        return [dict(r) for r in rows]

    # ---------------------------------------------------- payment breakdown

    def total_by_payment_method(
        self, start_date: str, end_date: str
    ) -> list[dict]:
        """Return revenue breakdown by payment method for the given period.

        Returns:
            List of dicts with keys: ``payment_method``, ``sale_count``, ``total_amount``.
        """
        rows = self._db.execute(
            """SELECT payment_method,
                      COUNT(*)   AS sale_count,
                      SUM(total) AS total_amount
               FROM sales
               WHERE created_at >= ? AND created_at <= ?
               GROUP BY payment_method
               ORDER BY total_amount DESC""",
            (start_date, end_date),
        ).fetchall()
        return [dict(r) for r in rows]

    # ----------------------------------------------------------- helpers ---

    def find_by_id(self, sale_id: int) -> Sale | None:
        """Return the sale with *sale_id*, or ``None``."""
        row = self._db.execute(
            "SELECT * FROM sales WHERE id = ?", (sale_id,)
        ).fetchone()
        if row is None:
            return None
        return self._from_row(row)

    @staticmethod
    def _from_row(row: sqlite3.Row) -> Sale:
        return Sale(
            id=row["id"],
            total=row["total"],
            discount=row["discount"],
            surcharge=row["surcharge"],
            payment_method=row["payment_method"],
            cash_register_id=row["cash_register_id"],
            created_at=row["created_at"],
        )
